import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import styles from "./styles/layout.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
    <body>
      <div className={styles.container}>
        <Sidebar/>
        <main className={styles.main}>
          {children}
        </main>
      </div>
    </body>
  </html>
  );
}
